# Generated by Django 2.2.14 on 2021-01-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20201124_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='upgrade_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='升级状态'),
        ),
    ]
