# Generated by Django 2.2.14 on 2020-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_filter_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='签名'),
        ),
    ]
