# Generated by Django 2.2.14 on 2020-11-24 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='messages',
            field=models.ManyToManyField(to='message.Message', verbose_name='关联消息'),
        ),
        migrations.AddField(
            model_name='event',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operate_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
    ]
