# Generated by Django 2.2.14 on 2020-11-24 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('event', '0002_auto_20201124_1029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_taggeduuiditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='event',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='receive_events', to=settings.AUTH_USER_MODEL, verbose_name='消息接收人'),
        ),
        migrations.AddField(
            model_name='event',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respond_event', to=settings.AUTH_USER_MODEL, verbose_name='响应人员'),
        ),
        migrations.AddField(
            model_name='event',
            name='similar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event', verbose_name='同类事件'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedUUIDItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
