# Generated by Django 2.2.14 on 2020-11-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201124_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='converge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converge.BurrConverge', verbose_name='毛刺收敛'),
        ),
    ]
