# Generated by Django 2.2.14 on 2021-02-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silence',
            old_name='type',
            new_name='event',
        ),
    ]
