# Generated by Django 2.2.14 on 2021-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upgrade_frequency',
            field=models.IntegerField(default=300, verbose_name='升级频率'),
        ),
    ]
